language: ruby
rvm:
  - 2.3.0
branches:
  only:
  - master
  - develop
addons:
  postgresql: '9.3'
bundler_args: "--without production --jobs=3"
cache: bundler
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database-travis.yml config/database.yml
  - bundle exec rake db:schema:load RAILS_ENV=test

